<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>aic_my_policy</name>
  <version>0.0.1</version>
  <description>Vision + impedance base policy with residual-RL fine-tuning for the AI for Industry Challenge.</description>
  <maintainer email="sawansingsihag@gmail.com">AIC Team</maintainer>
  <license>Apache-2.0</license>

  <depend>aic_control_interfaces</depend>
  <depend>aic_model</depend>
  <depend>aic_model_interfaces</depend>
  <depend>aic_task_interfaces</depend>
  <depend>cv_bridge</depend>
  <depend>geometry_msgs</depend>
  <depend>python3-transforms3d</depend>
  <depend>rclpy</depend>
  <depend>tf2_ros</depend>
  <depend>sensor_msgs</depend>
  <depend>std_srvs</depend>
  <depend>trajectory_msgs</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
